// =============================================================================
// PXG // HARD-GRID COORDINATE SYSTEM (HGCS)
// AI Module: Auto-Layout Pipeline
// End-to-end pipeline: serialize → infer → filter → apply → validate.
// Operational Order: PXG-2026-SOMU-0325
// =============================================================================

using System;
using System.Collections.Generic;
using UnityEngine;

namespace PXG.HGCS.AI
{
    /// <summary>
    /// End-to-end auto-layout pipeline orchestrating:
    /// 1. Serialize current layout state into input tensor
    /// 2. Run Sentis inference via <see cref="SentisModelLoader"/>
    /// 3. Deserialize output into <see cref="SentisIntegration.LayoutSuggestion"/>
    /// 4. Filter and apply suggestions through <see cref="SentisIntegration"/>
    /// 5. Validate final layout via <see cref="SanityCheck"/>
    ///
    /// This is the single entry point for AI-driven layout optimization.
    /// </summary>
    public class AutoLayoutPipeline
    {
        // ── Pipeline Result ─────────────────────────────────────────────────

        /// <summary>Result of one pipeline execution cycle.</summary>
        public class PipelineResult
        {
            /// <summary>Number of suggestions generated by the model.</summary>
            public int SuggestionsGenerated { get; set; }

            /// <summary>Number of suggestions accepted after filtering.</summary>
            public int SuggestionsAccepted { get; set; }

            /// <summary>Number of suggestions rejected.</summary>
            public int SuggestionsRejected => SuggestionsGenerated - SuggestionsAccepted;

            /// <summary>Whether the constraint solver converged after applying suggestions.</summary>
            public bool SolverConverged { get; set; }

            /// <summary>Sanity check results after layout update.</summary>
            public List<SanityCheck.CheckResult> ValidationResults { get; set; }

            /// <summary>Number of validation failures.</summary>
            public int ValidationFailures { get; set; }

            /// <summary>Total pipeline execution time in milliseconds.</summary>
            public double ExecutionTimeMs { get; set; }

            /// <summary>Overall success: all suggestions applied and validated.</summary>
            public bool Success => SuggestionsAccepted > 0
                                && SolverConverged
                                && ValidationFailures == 0;

            public override string ToString() =>
                $"[PXG AI PIPELINE] " +
                $"Suggestions: {SuggestionsAccepted}/{SuggestionsGenerated} accepted | " +
                $"Solver: {(SolverConverged ? "✓" : "✗")} | " +
                $"Validation: {(ValidationFailures == 0 ? "✓ PASS" : $"✗ {ValidationFailures} failures")} | " +
                $"Time: {ExecutionTimeMs:F1}ms";
        }

        // ── Dependencies ────────────────────────────────────────────────────

        private readonly SentisModelLoader _modelLoader;
        private readonly LayoutOptimizationModel _model;
        private readonly SentisIntegration _integration;
        private readonly ConstraintSolver _solver;
        private readonly DeterministicGrid _grid;
        private readonly SanityCheck _checker;

        // ── Configuration ───────────────────────────────────────────────────

        /// <summary>Viewport size for coordinate normalization.</summary>
        public Vector2Int ViewportSize { get; set; } = new Vector2Int(1920, 1080);

        /// <summary>Minimum confidence to pass to SentisIntegration.</summary>
        public float MinModelConfidence { get; set; } = 0.3f;

        /// <summary>Maximum pipeline executions per second (throttle).</summary>
        public float MaxExecutionsPerSecond { get; set; } = 2f;

        /// <summary>Whether to auto-validate after applying suggestions.</summary>
        public bool AutoValidate { get; set; } = true;

        // ── State ───────────────────────────────────────────────────────────

        private float _lastExecutionTime;

        // ── Events ──────────────────────────────────────────────────────────

        /// <summary>Fired after each pipeline cycle completes.</summary>
        public event Action<PipelineResult> OnCycleComplete;

        // ── Constructor ─────────────────────────────────────────────────────

        public AutoLayoutPipeline(
            SentisModelLoader modelLoader,
            LayoutOptimizationModel model,
            SentisIntegration integration,
            ConstraintSolver solver,
            DeterministicGrid grid,
            SanityCheck checker)
        {
            _modelLoader = modelLoader ?? throw new ArgumentNullException(nameof(modelLoader));
            _model = model ?? throw new ArgumentNullException(nameof(model));
            _integration = integration ?? throw new ArgumentNullException(nameof(integration));
            _solver = solver ?? throw new ArgumentNullException(nameof(solver));
            _grid = grid ?? throw new ArgumentNullException(nameof(grid));
            _checker = checker ?? throw new ArgumentNullException(nameof(checker));
        }

        // ── Execute Pipeline ────────────────────────────────────────────────

        /// <summary>
        /// Executes one full auto-layout cycle on the given anchors.
        /// Thread-safe: all operations are deterministic and grid-snapped.
        /// </summary>
        public PipelineResult Execute(IReadOnlyList<AnchorPoint> anchors)
        {
            var sw = System.Diagnostics.Stopwatch.StartNew();
            var result = new PipelineResult();

            try
            {
                // 1. Serialize anchors into model input tensor
                float[] inputTensor = _model.SerializeInput(anchors, ViewportSize);

                // 2. Run inference
                float[] outputTensor;
                if (_modelLoader.IsLoaded)
                {
                    outputTensor = _modelLoader.Execute(inputTensor);
                }
                else
                {
                    // Fallback: generate heuristic suggestions without AI
                    outputTensor = GenerateHeuristicSuggestions(anchors);
                    Debug.LogWarning("[PXG.HGCS.AI] No model loaded — using heuristic fallback.");
                }

                // 3. Deserialize output into suggestions
                var suggestions = _model.DeserializeOutput(
                    outputTensor, anchors, ViewportSize, MinModelConfidence);

                result.SuggestionsGenerated = suggestions.Count;

                // 4. Apply through SentisIntegration (filters by confidence/magnitude)
                if (suggestions.Count > 0)
                {
                    result.SuggestionsAccepted = _integration.ProcessSuggestions(suggestions);
                }

                // 5. Re-solve constraints
                result.SolverConverged = _solver.Solve();

                // 6. Validate
                if (AutoValidate)
                {
                    result.ValidationResults = _checker.RunAll(
                        anchors is List<AnchorPoint> list ? list : new List<AnchorPoint>(anchors));

                    foreach (var check in result.ValidationResults)
                    {
                        if (check.Severity == SanityCheck.Severity.Fail)
                            result.ValidationFailures++;
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.LogError($"[PXG.HGCS.AI] Pipeline error: {ex.Message}");
                result.SolverConverged = false;
                result.ValidationFailures = -1; // error state
            }

            sw.Stop();
            result.ExecutionTimeMs = sw.Elapsed.TotalMilliseconds;
            _lastExecutionTime = Time.time;

            OnCycleComplete?.Invoke(result);
            return result;
        }

        // ── Heuristic Fallback ──────────────────────────────────────────────

        /// <summary>
        /// Generates layout suggestions using rule-based heuristics when
        /// no Sentis model is loaded. Useful for demo without GPU.
        /// </summary>
        private float[] GenerateHeuristicSuggestions(IReadOnlyList<AnchorPoint> anchors)
        {
            int outputLength = _model.MaxAnchors * LayoutOptimizationModel.DeltasPerAnchor;
            float[] output = new float[outputLength];
            int count = Math.Min(anchors.Count, _model.MaxAnchors);

            // Heuristic: nudge overlapping anchors apart
            for (int i = 0; i < count; i++)
            {
                if (anchors[i].IsLocked) continue;

                float totalDx = 0f, totalDy = 0f;
                int conflicts = 0;

                for (int j = 0; j < count; j++)
                {
                    if (i == j) continue;
                    float dist = Vector2.Distance(anchors[i].Position, anchors[j].Position);
                    float minDist = _grid.CellSize * 2;

                    if (dist < minDist && dist > 0.001f)
                    {
                        Vector2 dir = (anchors[i].Position - anchors[j].Position).normalized;
                        float push = (minDist - dist) * 0.5f;
                        totalDx += dir.x * push;
                        totalDy += dir.y * push;
                        conflicts++;
                    }
                }

                if (conflicts > 0)
                {
                    int baseIdx = i * LayoutOptimizationModel.DeltasPerAnchor;
                    output[baseIdx + 0] = totalDx / ViewportSize.x;  // normalized
                    output[baseIdx + 1] = totalDy / ViewportSize.y;
                    output[baseIdx + 2] = Mathf.Clamp01(0.5f + conflicts * 0.1f); // confidence
                }
            }

            return output;
        }

        // ── Throttle Check ──────────────────────────────────────────────────

        /// <summary>
        /// Returns true if enough time has passed since the last execution.
        /// Use in Update() to throttle pipeline calls.
        /// </summary>
        public bool CanExecute()
        {
            float minInterval = 1f / MaxExecutionsPerSecond;
            return (Time.time - _lastExecutionTime) >= minInterval;
        }
    }
}
